-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 16:49:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema comilao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comilao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comilao` DEFAULT CHARACTER SET utf8 ;
USE `comilao` ;

-- -----------------------------------------------------
-- Table `comilao`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Pais` (
  `idPais` INT NOT NULL,
  `Cod_pais` VARCHAR(3) NOT NULL,
  `nome_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Sexo` (
  `idSexo` INT NOT NULL,
  `descricao_sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Tipo_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Tipo_Endereco` (
  `idTipo_Endereco` INT NOT NULL,
  `descricao_tipoEndereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`UF` (
  `idUF` INT NOT NULL,
  `Descricao_UF` VARCHAR(45) NOT NULL,
  `DDD` VARCHAR(2) NOT NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idUF`),
  INDEX `fk_UF_Pais1_idx` (`Pais_idPais` ASC) VISIBLE,
  CONSTRAINT `fk_UF_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `comilao`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Cidade` (
  `idCidade` INT NOT NULL,
  `descricao_cidade` VARCHAR(45) NOT NULL,
  `UF_idUF` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_UF1_idx` (`UF_idUF` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_UF1`
    FOREIGN KEY (`UF_idUF`)
    REFERENCES `comilao`.`UF` (`idUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Bairro` (
  `idBairro` INT NOT NULL,
  `descricao_bairro` VARCHAR(45) NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`idBairro`),
  INDEX `fk_Bairro_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_idCidade`)
    REFERENCES `comilao`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Endereco` (
  `idEndereco` INT NOT NULL,
  `CEP` VARCHAR(8) NULL,
  `nome_rua` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NOT NULL,
  `Bairro_idBairro` INT NOT NULL,
  `Tipo_Endereco_idTipo_Endereco` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_Tipo_Endereco1_idx` (`Tipo_Endereco_idTipo_Endereco` ASC) VISIBLE,
  INDEX `fk_Endereco_Bairro1_idx` (`Bairro_idBairro` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Tipo_Endereco1`
    FOREIGN KEY (`Tipo_Endereco_idTipo_Endereco`)
    REFERENCES `comilao`.`Tipo_Endereco` (`idTipo_Endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`Bairro_idBairro`)
    REFERENCES `comilao`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Estado_civil` (
  `idEstado_civil` INT NOT NULL,
  `desc_estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Escolaridade` (
  `idEscolaridade` INT NOT NULL,
  `desc_escolaridade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEscolaridade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Filiacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Filiacao` (
  `idFiliacao` INT NOT NULL,
  `nome_mae` VARCHAR(45) NOT NULL,
  `nome_pai` VARCHAR(45) NULL,
  PRIMARY KEY (`idFiliacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `identidade` VARCHAR(7) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `salario` DOUBLE NULL,
  `Pais_idPais` INT NOT NULL,
  `Sexo_idSexo` INT NOT NULL,
  `Estado_civil_idEstado_civil` INT NOT NULL,
  `Escolaridade_idEscolaridade` INT NOT NULL,
  `Filiacao_idFiliacao` INT NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX `fk_Pessoa_Pais1_idx` (`Pais_idPais` ASC) VISIBLE,
  INDEX `fk_Pessoa_Sexo1_idx` (`Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Pessoa_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Pessoa_Estado_civil1_idx` (`Estado_civil_idEstado_civil` ASC) VISIBLE,
  INDEX `fk_Pessoa_Escolaridade1_idx` (`Escolaridade_idEscolaridade` ASC) VISIBLE,
  INDEX `fk_Pessoa_Filiacao1_idx` (`Filiacao_idFiliacao` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `comilao`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `comilao`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `comilao`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Estado_civil1`
    FOREIGN KEY (`Estado_civil_idEstado_civil`)
    REFERENCES `comilao`.`Estado_civil` (`idEstado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Escolaridade1`
    FOREIGN KEY (`Escolaridade_idEscolaridade`)
    REFERENCES `comilao`.`Escolaridade` (`idEscolaridade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Filiacao1`
    FOREIGN KEY (`Filiacao_idFiliacao`)
    REFERENCES `comilao`.`Filiacao` (`idFiliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Cargo` (
  `idCargo` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `salario` DOUBLE NOT NULL,
  `bonus_salarial` DOUBLE NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Funcionario_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Funcionario_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `comilao`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `comilao`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Cliente_Funcionario1_idx` (`Funcionario_idFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `comilao`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `comilao`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Logotipo_Restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Logotipo_Restaurante` (
  `idLogotipo_Restaurante` INT NOT NULL,
  `referencia_logotipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogotipo_Restaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Recibo` (
  `idRecibo` INT NOT NULL,
  `cometario_cliente` VARCHAR(45) NOT NULL,
  `data_hora_recibo` DATETIME NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Logotipo_Restaurante_idLogotipo_Restaurante` INT NOT NULL,
  PRIMARY KEY (`idRecibo`),
  INDEX `fk_Recibo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Recibo_Logotipo_Restaurante1_idx` (`Logotipo_Restaurante_idLogotipo_Restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_Recibo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `comilao`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibo_Logotipo_Restaurante1`
    FOREIGN KEY (`Logotipo_Restaurante_idLogotipo_Restaurante`)
    REFERENCES `comilao`.`Logotipo_Restaurante` (`idLogotipo_Restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Pedido` (
  `idPedido` INT NOT NULL,
  `observacao` LONGTEXT NOT NULL,
  `valor_total` DOUBLE NOT NULL,
  `status_pedido` TINYINT NOT NULL,
  `data_hora_pedido` DATETIME NOT NULL,
  `Recibo_idRecibo` INT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Recibo1_idx` (`Recibo_idRecibo` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Recibo1`
    FOREIGN KEY (`Recibo_idRecibo`)
    REFERENCES `comilao`.`Recibo` (`idRecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  `DDD` VARCHAR(2) NOT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Telefone_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `comilao`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Tipo_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Tipo_item` (
  `idTipo_item` INT NOT NULL,
  `descricao_item` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_item`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Item_Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Item_Menu` (
  `idItem_Menu` INT NOT NULL,
  `descricao_item` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `popularidade` INT NOT NULL,
  `Tipo_item_idTipo_item` INT NOT NULL,
  PRIMARY KEY (`idItem_Menu`),
  INDEX `fk_Item_Menu_Tipo_item1_idx` (`Tipo_item_idTipo_item` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Menu_Tipo_item1`
    FOREIGN KEY (`Tipo_item_idTipo_item`)
    REFERENCES `comilao`.`Tipo_item` (`idTipo_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Item_Menu_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Item_Menu_Pedido` (
  `Item_Menu_idItem_Menu` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_parcial` DOUBLE NOT NULL,
  INDEX `fk_Item_Menu_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Item_Menu_has_Pedido_Item_Menu1_idx` (`Item_Menu_idItem_Menu` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Menu_has_Pedido_Item_Menu1`
    FOREIGN KEY (`Item_Menu_idItem_Menu`)
    REFERENCES `comilao`.`Item_Menu` (`idItem_Menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Menu_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `comilao`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Mesa` (
  `idMesa` INT NOT NULL,
  `quantidade_lugares` INT NOT NULL,
  `disponibilidade` TINYINT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idMesa`),
  INDEX `fk_Mesa_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Mesa_Funcionario1_idx` (`Funcionario_idFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_Mesa_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `comilao`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mesa_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `comilao`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Cliente_Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Cliente_Mesa` (
  `Cliente_idCliente` INT NOT NULL,
  `Mesa_idMesa` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Mesa_idMesa`),
  INDEX `fk_Cliente_has_Mesa_Mesa1_idx` (`Mesa_idMesa` ASC) VISIBLE,
  INDEX `fk_Cliente_has_Mesa_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_Mesa_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `comilao`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Mesa_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `comilao`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Produto` (
  `idProduto` INT NOT NULL,
  `desc_prod` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `qtd_estoque` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`idEstoque`),
  INDEX `fk_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `comilao`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Item_Menu_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Item_Menu_Produto` (
  `Item_Menu_idItem_Menu` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  INDEX `fk_Item_Menu_has_Produto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  INDEX `fk_Item_Menu_has_Produto_Item_Menu1_idx` (`Item_Menu_idItem_Menu` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Menu_has_Produto_Item_Menu1`
    FOREIGN KEY (`Item_Menu_idItem_Menu`)
    REFERENCES `comilao`.`Item_Menu` (`idItem_Menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Menu_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `comilao`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comilao`.`Item_Menu_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comilao`.`Item_Menu_Cliente` (
  `id_item_menu_cliente` INT NOT NULL,
  `Item_Menu_idItem_Menu` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `qtd_item` INT NOT NULL,
  `media_gasto` DOUBLE NOT NULL,
  INDEX `fk_Item_Menu_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Item_Menu_has_Cliente_Item_Menu1_idx` (`Item_Menu_idItem_Menu` ASC) VISIBLE,
  PRIMARY KEY (`id_item_menu_cliente`),
  CONSTRAINT `fk_Item_Menu_has_Cliente_Item_Menu1`
    FOREIGN KEY (`Item_Menu_idItem_Menu`)
    REFERENCES `comilao`.`Item_Menu` (`idItem_Menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Menu_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `comilao`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
